package dev.slne.surf.icon.generator.model

import dev.slne.surf.icon.generator.model.element.BlockBenchModelElement
import kotlinx.serialization.Serializable
import org.spongepowered.configurate.objectmapping.meta.Setting

@Serializable
data class BlockBenchModel(
    @Setting("format_version")
    val formatVersion: String = "1.21.11",
    val credit: String = "Generated by Surf Icon Generator",
    val textures: MutableMap<String, String>,
    val elements: MutableList<BlockBenchModelElement>,
    val groups: MutableList<BlockBenchModelGroup>,
    val display: MutableMap<String, BlockBenchModelDisplay>? = null
) {
    val highestTextureIndex: Int?
        get() = textures.keys.mapNotNull {
            it.toIntOrNull()
        }.maxOrNull()

    val highestElementTo: Float
        get() = elements.maxOfOrNull { element ->
            element.to.getOrNull(1) ?: 0f
        } ?: 0f

    fun applyTint(index: Int = 0): BlockBenchModel {
        elements.forEach { element ->
            element.applyTint(index)
        }

        return this
    }

    fun fixTexturePrefixes(): BlockBenchModel {
        textures.forEach { (key, texture) ->
            val split = texture.split("surf:textures/gui/icons/")

            if (split.size != 2) {
                textures[key] = "surf:textures/gui/icons/$texture"
            }
        }

        return this
    }

    fun incrementTextureIndex(offset: Int?): BlockBenchModel {
        if (offset == null) return this

        textures.forEach { (key, _) ->
            val index = key.toIntOrNull() ?: return@forEach
            val newIndex = index + offset + 1

            textures[newIndex.toString()] = textures[key] ?: return@forEach
        }

        return this
    }

    fun merge(other: BlockBenchModel): BlockBenchModel {
        other.incrementTextureIndex(highestTextureIndex)

        other.textures.forEach { text ->
            if (!textures.containsKey(text.key)) {
                textures[text.key] = text.value
            }
        }

        val highestElementTo = highestElementTo
        other.elements.forEach { element ->
            element.move(0f, highestElementTo, 0f)
            elements.add(element)
        }

        val maxElementIndex = elements.size
        val groupsToMerge = mutableListOf<BlockBenchModelGroup>()
        other.groups.forEach { group ->
            val existingGroup = groups.find { it.name == group.name }
            if (existingGroup != null) return@forEach

            group.offsetChildren(maxElementIndex)
            groupsToMerge.add(group)
        }

        groups.addAll(groupsToMerge)

        fixTexturePrefixes()

        return this
    }

    override fun toString(): String {
        return "BlockBenchModel(formatVersion='$formatVersion', credit='$credit', textures=$textures, elements=$elements, groups=$groups, highestTextureIndex=$highestTextureIndex)"
    }
}