package dev.slne.surf.icon.generator.model

import dev.slne.surf.icon.generator.model.element.BlockBenchModelElement
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BlockBenchModel(
    @SerialName("format_version")
    val formatVersion: String = "1.21.11",
    val credit: String = "Generated by Surf Icon Generator",
    val parent: String,
    @SerialName("texture_size")
    val textureSize: MutableList<Int>? = null,
    val textures: MutableMap<String, String>,
    val elements: MutableList<BlockBenchModelElement>,
    val groups: MutableList<BlockBenchModelGroup>,
    @SerialName("gui_light")
    val guiLight: String? = null,
    val display: MutableMap<String, BlockBenchModelDisplay>? = null
) {
    val highestTextureIndex: Int?
        get() = textures.keys.mapNotNull {
            it.toIntOrNull()
        }.maxOrNull()

    val highestElementTo: Float
        get() = elements.maxOfOrNull { element ->
            element.to.getOrNull(1) ?: 0f
        } ?: 0f

    fun applyTint(index: Int = 0): BlockBenchModel {
        val elementsIterator = elements.iterator()
        while (elementsIterator.hasNext()) {
            val element = elementsIterator.next()

            element.applyTint(index)
        }

        return this
    }

    fun fixTexturePrefixes(): BlockBenchModel {
        val texturesIterator = textures.iterator()
        while (texturesIterator.hasNext()) {
            val entry = texturesIterator.next()
            val key = entry.key
            val texture = entry.value

            val split = texture.split("surf:gui/icons/")

            if (split.size != 2) {
                textures[key] = "surf:gui/icons/$texture"
            }
        }

        return this
    }

    fun incrementTextureIndex(offset: Int?): BlockBenchModel {
        if (offset == null) return this

        textures.toMap().forEach { (key, _) ->
            val index = key.toIntOrNull() ?: return@forEach
            val newIndex = index + offset + 1

            textures[newIndex.toString()] = textures[key] ?: return@forEach
        }

        elements.toList().forEach { element ->
            element.faces.toList().forEach { (_, face) ->
                val index = face.texture.trim().removePrefix("#").toIntOrNull() ?: return@forEach
                val newIndex = index + offset + 1

                face.texture = "#$newIndex"
            }
        }

        return this
    }

    fun merge(other: BlockBenchModel): BlockBenchModel {
        other.incrementTextureIndex(highestTextureIndex)

        other.textures.toMap().forEach { text ->
            if (!textures.containsKey(text.key)) {
                textures[text.key] = text.value
            }
        }

        other.textureSize?.toList()?.let {
            textureSize?.addAll(it)
        }

        val highestElementTo = highestElementTo
        other.elements.toList().forEach { element ->
            element.move(0f, highestElementTo, 0f)
            elements.add(element)
        }

        val maxElementIndex = elements.size
        val groupsToMerge = mutableListOf<BlockBenchModelGroup>()
        other.groups.toList().forEach { group ->
            val existingGroup = groups.find { it.name == group.name }
            if (existingGroup != null) return@forEach

            group.offsetChildren(maxElementIndex)
            groupsToMerge.add(group)
        }

        groups.addAll(groupsToMerge)

        fixTexturePrefixes()

        return this
    }

    override fun toString(): String {
        return "BlockBenchModel(formatVersion='$formatVersion', credit='$credit', textures=$textures, elements=$elements, groups=$groups, highestTextureIndex=$highestTextureIndex)"
    }
}