package dev.slne.surf.icon.generator.generator

enum class GeneratorResult {
    SUCCESS,
    INVALID_NAME,
    INVALID_FOREGROUND_COLOR,
    INVALID_SHADOW_COLOR,
    INVALID_BACKGROUND_COLOR,

    CONFIG_INPUT_NOT_FOUND,
    CONFIG_OUTPUT_NOT_FOUND,
    CONFIG_COPY_FAILED,
    CONFIG_STUB_REPLACE_FAILED,

    ICONS_INPUT_NOT_FOUND,
    ICONS_COPY_FAILED,
    ICONS_COLOR_REPLACE_FAILED;

    fun isSuccess(): Boolean = this == SUCCESS
}